# Generated by Django 6.0.3 on 2026-03-30 03:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('streak_broken', 'Streak Broken'), ('streak_milestone', 'Streak Milestone'), ('low_focus', 'Low Focus Warning'), ('high_distraction', 'High Distraction Warning'), ('task_overdue', 'Task Overdue'), ('goal_achieved', 'Goal Achieved'), ('improvement', 'Improvement Detected'), ('reminder', 'Study Reminder')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('danger', 'Danger')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('peak_focus', 'Peak Focus Time'), ('low_focus', 'Low Focus Time'), ('distraction_trigger', 'Distraction Trigger'), ('productive_habit', 'Productive Habit'), ('procrastination', 'Procrastination Pattern'), ('improvement', 'Improvement Trend')], max_length=30)),
                ('description', models.TextField()),
                ('confidence', models.FloatField(default=0.5, help_text='Confidence score 0.0 to 1.0')),
                ('data_points', models.PositiveIntegerField(default=0, help_text='Number of data points supporting this pattern')),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('total_completions', models.PositiveIntegerField(default=0)),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_streak'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('focus_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Self-rated focus score from 1 (distracted) to 10 (deep focus)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DistractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distraction_type', models.CharField(choices=[('social_media', 'Social Media'), ('phone', 'Phone Notifications'), ('people', 'People / Conversations'), ('food', 'Food / Snacks'), ('daydreaming', 'Daydreaming'), ('entertainment', 'Entertainment (TV, Games)'), ('internet', 'Internet Browsing'), ('noise', 'Noise / Environment'), ('fatigue', 'Fatigue / Sleepiness'), ('other', 'Other')], max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Distraction duration in minutes')),
                ('context', models.TextField(blank=True, help_text='What were you doing when you got distracted?', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distractions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distractions', to='analyzer.studysession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_text', models.TextField()),
                ('category', models.CharField(choices=[('focus', 'Focus Improvement'), ('distraction', 'Distraction Management'), ('habit', 'Habit Building'), ('task', 'Task Management'), ('schedule', 'Schedule Optimization'), ('wellness', 'Wellness & Breaks')], max_length=30)),
                ('is_helpful', models.BooleanField(blank=True, help_text='User feedback on suggestion', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Suggestion histories',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_study_minutes', models.FloatField(default=0)),
                ('avg_focus_score', models.FloatField(default=0)),
                ('total_distraction_minutes', models.FloatField(default=0)),
                ('distraction_ratio', models.FloatField(default=0, help_text='Ratio of distraction time to study time')),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('habits_completed', models.PositiveIntegerField(default=0)),
                ('productivity_score', models.FloatField(default=0, help_text='Overall productivity score (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Productivity metrics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
